# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20160709_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionScheduler',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, editable=False, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[(b'hourly', b'Hourly'), (b'weekly', b'Weekly'), (b'minutly', b'Minutly'), (b'daily', b'Daily'), (b'yearly', b'Yearly')], default=b'hourly', max_length=20)),
                ('every', models.IntegerField(default=1)),
                ('maxRuns', models.IntegerField(default=0)),
                ('schedulerType', models.CharField(choices=[(b'interval', b'Interval'), (b'cron', b'Cron')], default=b'Interval', max_length=10)),
                ('action', models.CharField(choices=[(b'tweet', b'tweet'), (b'search', b'search'), (b'follow', b'follow')], default=b'tweet', max_length=32)),
                ('requestBody', models.TextField(blank=True, max_length=2048, null=True)),
                ('exprn', models.CharField(blank=True, max_length=32, null=True)),
                ('args', models.CharField(blank=True, max_length=1024, null=True)),
                ('kwargs', models.CharField(blank=True, max_length=1024, null=True)),
                ('lastRunTime', models.DateTimeField(blank=True, null=True)),
                ('nextRunTime', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ap_rest_scheduler',
            },
        ),
    ]
