# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20160718_2031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionscheduler',
            table=None,
        ),
    ]
