# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20160718_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionScheduler',
        ),
    ]
