# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0044_auto_20160718_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(default=b'285e8a33-ea1e-496f-a7cb-9382acfc7682', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='twittersecret',
            name='uuid',
            field=models.UUIDField(default=b'c6e9b02c-c214-4631-9588-234f153080bf', editable=False, unique=True),
        ),
    ]
