# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0045_auto_20160718_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(default=b'a05715ca-e809-49a8-9ec9-b48b82ca0101', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='twittersecret',
            name='uuid',
            field=models.UUIDField(default=b'7b19b306-f28a-4492-bf59-6a63c8c4b408', editable=False, unique=True),
        ),
    ]
