# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0046_auto_20160718_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(default=b'05f3c05e-e08b-4368-816e-7f3a7daaf668', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='twittersecret',
            name='uuid',
            field=models.UUIDField(default=b'59a046f7-e34c-4046-bdd9-be0a411833d3', editable=False, unique=True),
        ),
    ]
