# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0049_auto_20160719_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(default=b'f527cbc8-176b-42d9-ab32-95982dbff5f8', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='twittersecret',
            name='uuid',
            field=models.UUIDField(default=b'1d26ae2b-987e-4c4a-825e-dc67a15d1991', editable=False, unique=True),
        ),
    ]
