# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0051_auto_20160719_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(default=b'8ef600da-9836-43ac-9f8e-e77d8e76edc9', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='twittersecret',
            name='uuid',
            field=models.UUIDField(default=b'3e298551-d0e2-4600-add9-ac6cf9364aeb', editable=False, unique=True),
        ),
    ]
